config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/log',  to: 'static_pages#log'
  get '/static_pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "Site under construction"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def log
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pcat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<%= link_to "Log", log_path %>

app/views/static_pages/log.html.erb
<p>
  379  cd install/
  380  rails new pcat
  381  cd pcat
  382  bundle install --without production --path vendor/bundle
  383  git init
  384  git add -A
  385  git commit -m "Initialise repository"
  386  git remote add origin https://github.com/a5215/pcat.git
  387  git push origin master
  388  heroku new
  389  heroku create
  390  git remote
  391  git push heroku master
  392  rails server
  393  generate new controller StaticPages home
  394  rails generate new controller StaticPages home
  395  rails generate controller StaticPages home
  396  rails server
  397  rails test
  398  rails server
  399  rails test
  400  rails server
  404  git add -A
  405  git commit -m 'Make static_pages/home'
  416  git push heroku master
  418  git push origin master

Если накосячишь с дублирующими коммитами git rebase --interactive HEAD~2
</p>